// policy.go — the deterministic governance-config generator (SPEC-OMNIGENT.md §5.3).
//
// becky-omni turns the request's governance knobs into TWO config files Omnigent enforces
// at the meta-harness layer: a POLICY file (cost cap, ask-on-os-tools, tool-call cap) and an
// OMNIBOX SANDBOX config (network egress allow-list + filesystem grants). Both are emitted as
// PLAIN TEXT YAML (no YAML parser dependency — per the build constraint; stdlib only). Output
// is byte-stable for the same governance (hosts/thresholds sorted) so the config is reproducible.
//
// WINDOWS DEGRADE: Omnibox's hard OS sandbox is Linux/macOS-native. On Windows the sandbox
// config is still written (so the artifact exists for inspection + the future WSL2/cloud path)
// but BuildSpec marks SandboxSupported=false and records a no-sandbox note the runner logs —
// the policy gates (cost/ask) still apply. This is the tested Windows degrade path.
//
// Fact-Forcing-Gate self-certification:
//  1. Callers: cmd/omni/main.go calls GeneratePolicy/BuildSpec; tested in omni_test.go.
//  2. No-dup: no existing policy generator; split from omni.go for file size (SPEC §5.3).
//  3. Data shape: emits policy.yaml + omnibox.yaml (plain-text YAML); no data files.
//  4. Verbatim instruction: "use subagents in parallel.. build everything".
package omni

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// RenderPolicy returns the Omnigent policy YAML for the effective governance (SPEC §5.3).
// It always emits the safety + tool-call-cap builtins; cost_budget only when a cap is set.
func RenderPolicy(g Governance) string {
	var b strings.Builder
	b.WriteString("# GENERATED by becky-omni from request.governance. Enforced at the meta-harness layer.\n")
	b.WriteString("policies:\n")
	if g.MaxCostUSD > 0 {
		b.WriteString("  budget:\n")
		b.WriteString("    type: function\n")
		b.WriteString("    handler: omnigent.policies.builtins.cost.cost_budget\n")
		b.WriteString("    factory_params:\n")
		fmt.Fprintf(&b, "      max_cost_usd: %s\n", trimFloat(g.MaxCostUSD))
		if len(g.AskThresholds) > 0 {
			fmt.Fprintf(&b, "      ask_thresholds_usd: [%s]\n", joinFloats(sortedFloats(g.AskThresholds)))
		}
	}
	// ask-on-os-tools: any write/shell/destructive call PAUSES for approval (a tap on the
	// phone). Emitted whenever the request asks for it OR writes are enabled (defense in depth).
	if wantsAskOS(g) {
		b.WriteString("  approve_os:\n")
		b.WriteString("    type: function\n")
		b.WriteString("    handler: omnigent.policies.builtins.safety.ask_on_os_tools\n")
	}
	b.WriteString("  cap_calls:\n")
	b.WriteString("    type: function\n")
	b.WriteString("    handler: omnigent.policies.builtins.safety.max_tool_calls_per_session\n")
	b.WriteString("    factory_params:\n")
	b.WriteString("      limit: 200\n")
	return b.String()
}

// wantsAskOS reports whether an OS-tool approval gate should be generated: the request
// listed "os_tools" in ask_on, or any filesystem writes are enabled (so a write pauses).
func wantsAskOS(g Governance) bool {
	for _, a := range g.AskOn {
		if a == "os_tools" {
			return true
		}
	}
	return g.FSWrites != FSWritesDeny && g.FSWrites != ""
}

// RenderSandbox returns the Omnibox sandbox config YAML for the effective governance
// (SPEC §5.3): network egress (default-deny offline; named hosts for research; open for
// full) + filesystem grants (case dir read-only; one RW output dir when output-dir-only).
// The literal Omnibox config keys are an ASSUMPTION the local agent pins (SPEC §5.3); this
// renders a clearly-labelled, stable shape that maps onto the documented behavior.
func RenderSandbox(g Governance, target string) string {
	var b strings.Builder
	b.WriteString("# GENERATED by becky-omni. Omnibox sandbox config (keys pinned by local agent — SPEC §5.3).\n")
	b.WriteString("sandbox:\n")
	b.WriteString("  network:\n")
	switch g.Sandbox {
	case SandboxResearch:
		b.WriteString("    egress: allow-list   # research: only the named hosts may egress (logged)\n")
		b.WriteString("    allow_hosts:\n")
		for _, h := range sortedStrings(g.AllowHosts) {
			fmt.Fprintf(&b, "      - %s\n", yamlString(h))
		}
	case SandboxFull:
		b.WriteString("    egress: open         # full: unrestricted egress (non-forensic only)\n")
	default: // offline
		b.WriteString("    egress: deny         # offline (default): network hard-closed at the OS level\n")
		b.WriteString("    allow_hosts: []\n")
	}
	b.WriteString("  filesystem:\n")
	if t := strings.TrimSpace(target); t != "" {
		fmt.Fprintf(&b, "    read_only:\n      - %s\n", yamlString(t))
	}
	switch g.FSWrites {
	case FSWritesOutputOnly:
		fmt.Fprintf(&b, "    read_write:\n      - %s\n", yamlString(g.OutputDir))
	case FSWritesFull:
		b.WriteString("    read_write: full     # full FS writes (reserved for exhibit-writing workflows)\n")
	default: // deny
		b.WriteString("    read_write: []       # deny (default): no writes outside an explicit output dir\n")
	}
	return b.String()
}

// GeneratePolicy writes policy.yaml + omnibox.yaml into dir and returns their paths. The
// governance is normalized (defaults + sensitive switch) before rendering so the written
// config reflects the EFFECTIVE governance, not the raw request. Never panics.
func GeneratePolicy(dir string, req Request) (policyPath, sandboxPath string, err error) {
	if strings.TrimSpace(dir) == "" {
		return "", "", fmt.Errorf("generate policy: empty run dir")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", "", fmt.Errorf("create run dir: %w", err)
	}
	g, _ := req.effectiveGovernance()
	policyPath = filepath.Join(dir, "policy.yaml")
	if err := os.WriteFile(policyPath, []byte(RenderPolicy(g)), 0o644); err != nil {
		return "", "", fmt.Errorf("write policy: %w", err)
	}
	sandboxPath = filepath.Join(dir, "omnibox.yaml")
	if err := os.WriteFile(sandboxPath, []byte(RenderSandbox(g, req.Target)), 0o644); err != nil {
		return "", "", fmt.Errorf("write sandbox config: %w", err)
	}
	return policyPath, sandboxPath, nil
}

// BuildSpec assembles the OmniSpec from a validated request, the harness manifest paths,
// and the generated config — applying defaults, the sensitive switch, and the Windows
// no-sandbox degrade. It is the single place the effective governance is realized.
func BuildSpec(req Request, agentYAMLPath, manifestPath, policyPath, sandboxPath, runDir, backend, serverURL string) OmniSpec {
	g, auth := req.effectiveGovernance()
	supported, note := sandboxStatus()
	if backend == "" {
		backend = "cli"
	}
	if serverURL == "" {
		serverURL = "http://localhost:6767"
	}
	return OmniSpec{
		AgentYAMLPath:    agentYAMLPath,
		ManifestPath:     manifestPath,
		PolicyPath:       policyPath,
		SandboxPath:      sandboxPath,
		Goal:             req.Goal,
		Target:           req.Target,
		Provider:         req.Model.Provider,
		Model:            req.Model.ID,
		BaseURL:          req.Model.BaseURL,
		Auth:             auth,
		Gov:              g,
		Backend:          backend,
		ServerURL:        serverURL,
		RunDir:           runDir,
		SandboxSupported: supported,
		SandboxNote:      note,
	}
}

// --- small deterministic text helpers (no YAML library) ---

// trimFloat renders a float without trailing zeros (e.g. 2 not 2.00).
func trimFloat(f float64) string {
	return fmt.Sprintf("%g", f)
}

// joinFloats renders a sorted float slice as "a, b, c".
func joinFloats(fs []float64) string {
	parts := make([]string, 0, len(fs))
	for _, f := range fs {
		parts = append(parts, trimFloat(f))
	}
	return strings.Join(parts, ", ")
}

// sortedStrings returns a sorted copy for deterministic host ordering.
func sortedStrings(in []string) []string {
	out := make([]string, len(in))
	copy(out, in)
	sort.Strings(out)
	return out
}

// yamlString quotes a scalar so a Windows path (backslashes, colon) is a safe YAML value.
func yamlString(s string) string {
	if s == "" {
		return `""`
	}
	// Double-quote and escape backslashes + double-quotes so C:\... is valid YAML.
	r := strings.ReplaceAll(s, `\`, `\\`)
	r = strings.ReplaceAll(r, `"`, `\"`)
	return `"` + r + `"`
}
