package ctlmodel

// grammar.go — the GBNF grammar that locks a llama.cpp model to emit ONLY a valid
// BeckyEditBatch JSON object. Pass it to llama.cpp via `--grammar-file` (see
// WriteGrammarFile) so the model physically cannot produce malformed JSON or an op
// outside the closed enum; ctledit then validates the per-op field semantics.
//
// The grammar enforces the load-bearing structure — a {summary, edits[]} object whose
// every edit has an "op" drawn from the closed enum and whose members use only known
// keys with JSON-typed values. It deliberately does NOT encode each op's exact field
// set in the grammar (that combinatorial union is brittle and ctledit already rejects
// bad fields with a plain-English reason). The op enum and key set are generated from
// the canonical vocabulary below, so they can never drift from ctledit's schema
// silently — grammar_test asserts every ctledit op constant appears.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"becky-go/internal/ctledit"
)

// grammarOps is the closed op enum, sourced from ctledit's exported constants so the
// grammar and the applier share one source of truth.
var grammarOps = []string{
	ctledit.OpAddNotes,
	ctledit.OpDeleteNotes,
	ctledit.OpMoveNotes,
	ctledit.OpResizeNotes,
	ctledit.OpTranspose,
	ctledit.OpSetVelocity,
	ctledit.OpSetStep,
	ctledit.OpSetGain,
	ctledit.OpSetPan,
	ctledit.OpMute,
	ctledit.OpSolo,
	ctledit.OpRouteTo,
	ctledit.OpRoute,
	ctledit.OpAddSidechain,
	ctledit.OpSetTempo,
}

// grammarKeys is every JSON key a BeckyEdit member may use (mirrors the json tags in
// ctledit.BeckyEdit). The model may emit any subset; ctledit enforces which apply.
var grammarKeys = []string{
	"track", "clip", "notes", "note_ids", "d_ticks", "d_pitch", "d_dur",
	"semitones", "velocity", "lane_idx", "step", "on", "step_vel",
	"target", "gain", "pan", "muted", "soloed", "bus_id", "sidechain_source", "bpm",
}

// Grammar returns the GBNF text constraining a model to a valid BeckyEditBatch.
func Grammar() string {
	var b strings.Builder
	b.WriteString("# becky-canvas BeckyEditBatch grammar (generated by internal/ctlmodel)\n")
	b.WriteString(`root    ::= ws "{" ws "\"summary\"" ws ":" ws string ws "," ws "\"edits\"" ws ":" ws edits ws "}" ws` + "\n")
	b.WriteString(`edits   ::= "[" ws ( edit ( ws "," ws edit )* )? ws "]"` + "\n")
	b.WriteString(`edit    ::= "{" ws "\"op\"" ws ":" ws op ( ws "," ws member )* ws "}"` + "\n")
	b.WriteString("op      ::= " + altList(grammarOps) + "\n")
	b.WriteString("member  ::= key ws \":\" ws value\n")
	b.WriteString("key     ::= " + altList(grammarKeys) + "\n")
	b.WriteString("value   ::= string | number | boolean | array\n")
	b.WriteString(`array   ::= "[" ws ( value ( ws "," ws value )* )? ws "]"` + "\n")
	b.WriteString(`boolean ::= "true" | "false"` + "\n")
	b.WriteString(`string  ::= "\"" ( [^"\\] | "\\" . )* "\""` + "\n")
	b.WriteString(`number  ::= "-"? ( "0" | [1-9] [0-9]* ) ( "." [0-9]+ )?` + "\n")
	b.WriteString(`ws      ::= [ \t\n\r]*` + "\n")
	return b.String()
}

// altList renders a slice of literal strings as a GBNF alternation of quoted JSON
// string literals, e.g. ["a","b"] -> `"\"a\"" | "\"b\""`.
func altList(items []string) string {
	parts := make([]string, len(items))
	for i, it := range items {
		parts[i] = fmt.Sprintf("%q", `"`+it+`"`)
	}
	return strings.Join(parts, " | ")
}

// WriteGrammarFile writes Grammar() to <dir>/becky-edit.gbnf and returns the path.
// The local agent points llama.cpp's --grammar-file at it. dir must exist.
func WriteGrammarFile(dir string) (string, error) {
	path := filepath.Join(dir, "becky-edit.gbnf")
	if err := os.WriteFile(path, []byte(Grammar()), 0o644); err != nil {
		return "", fmt.Errorf("ctlmodel: write grammar: %w", err)
	}
	return path, nil
}
